[project]
name = "aoc-25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["typer>=0.12"]

[project.scripts]
aoc25 = "aoc_25.runner:app"
