[project]
name = "aoc-25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.1",
    "typer>=0.12",
]

[project.scripts]
aoc25 = "aoc_25.runner:app"

[tool.pytest.ini_options]
testpaths = ["tests"]
